spring:
  mqtt:
    broker:
      brokerId: mqtt-broker-1
    store:
      ignite:
        static-ip-addresses: 172.20.17.27:47500..47509
        persistenceStorePath: /data/ignite/store
logging:
  level:
    root: info
    org.apache.ignite: error
