spring:
  mqtt:
    broker:
      brokerId: mqtt-broker-1
    store:
      ignite:
        backup: 1
        static-ip-addresses: 127.0.0.1:47500..47509
        persistenceStorePath: /data/ignite/store
        casandraConfig:
          contactPoints: 10.148.12.163
          port: 9042
          username: root
          password: public
logging:
  level:
    root: info
    org.apache.ignite: error
    com.datastax.driver: info

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, env, metrics
  endpoint:
    prometheus:
      access: read_only
server:
  port: 8089
